name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: jagj77/elastalert2-server
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_TARGET_PLATFORM: linux/arm64,linux/amd64
      DOCKER_BUILDKIT: 1
      DK_FILE: "Dockerfile"
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest

      - name: Prepare
        if: success()
        id: prepare
        run: |
          echo docker_platform=${DOCKER_TARGET_PLATFORM} >> $GITHUB_ENV
          echo docker_image=${DOCKER_IMAGE} >> $GITHUB_ENV
          echo version=${GITHUB_RUN_NUMBER} >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Buildx (push image)
        if: success()
        run: |
          docker buildx build \
          --platform ${{ env.docker_platform }} \
          --tag ${{ env.docker_image }}:${{ env.version }} \
          --file ${{ env.DK_FILE }} \
          --output type=image,push=true .
